###################
### MY PROGRAMS ###
###################

$browser = librewolf 
$terminal = kitty
$fileManager = dolphin
$menu = ~/.config/rofi/launcher.sh || pkill rofi
$waybar = ~/.config/waybar/launch.sh
$logoutMenu = wlogout

