##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
  name = center-file-explorer
  match:class = ^(.*)$
  match:title = ^(All Files|Open File|Open|Save|Save As|Export|Import|Choose File|Rename)
  float = on
  center = on
  animation = popin 20%
  opacity = 0.8
}

windowrule = float on, center on, match:class (xdg-desktop-portal-gtk)
windowrule = float on, center on, match:class (xdg-desktop-portal-hyprland)
windowrule = float on, center on, match:class (Xdg-desktop-portal-gtk)
windowrule = float on, center on, match:class (xdg-desktop-portal-hyprland)
windowrule = border_size 0, match:class (xdg-desktop-portal-gtk)
layerrule = blur on, match:class logout_dialog
layerrule = ignore_alpha 0.5, match:class logout_dialog

windowrule {
    name = resize-tiling-windows
    match:class = .*
    match:float = true
    size = 500 500
    center = on
}

windowrule {
    name = move-kitty
    match:class = kitty

    move = (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5))
    animation = popin 60%
}

# waybar configuration
layerrule {
    name = waybar-config
    match:namespace = waybar
    
    ignore_alpha = 0.8
    blur = on
} 

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

