# All source files in source directory

source = ~/.config/hypr/source/monitors.conf
source = ~/.config/hypr/source/programs.conf
source = ~/.config/hypr/source/autoStart.conf
source = ~/.config/hypr/source/styles.conf
source = ~/.config/hypr/source/keybindings.conf
source = ~/.config/hypr/source/workspaces.conf

